services:
  connectorc:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:latest
    container_name: connectorc
    ports:
      - 8083:8083
    networks:
      - local

    volumes:
      - ./conf/config.json:/config/config.json
      - ./conf/testbed4.p12:/conf/testbed4.p12
      - ./conf/connectorC.p12:/config/connectorC.p12
      - ./conf/truststore.p12:/config/truststore.p12
      #- ./conf/jwks.json:/config/jwks.json

    environment:
      - CONFIGURATION_PATH=/config/config.json
      - SERVER_PORT=8083
      - DAPS_URL='https://omejd-idsa.platform.flexigrobots-h2020.eu'
      - DAPS_TOKEN_URL=https://omejd-idsa.platform.flexigrobots-h2020.eu/auth/token
      - DAPS_KEY_URL=https://omejd-idsa.platform.flexigrobots-h2020.eu/auth/jwks.json
      #- DAPS_WHITELISTED_URL=http://omejd-idsa.platform.flexigrobots-h2020.eu

      - DAPS_WHITELISTED_URL=https://omejd-idsa.platform.flexigrobots-h2020.eu/auth,http://omejdn/auth
      - DAPS_INCOMING_DAT_DEFAULT_WELLKNOWN=/jwks.json
      
      #- OMEJDN_DOMAIN=http://omejd-idsa.platform.flexigrobots-h2020.eu/auth/
      - SERVER_SSL_KEY-STORE=file:///config/connectorC.p12
networks:
  local:
    driver: bridge