apiVersion: v1
kind: Service
metadata:
  labels:
    app: broker-core
  name: broker-core
spec:
  type: ClusterIP
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: broker-core
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: broker-fuseki
  name: broker-fuseki
spec:
  type: ClusterIP
  ports:
    - name: "3030"
      port: 3030
      targetPort: 3030
  selector:
    app: broker-fuseki
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: broker-reverseproxy
  name: broker-reverseproxy
spec:
  type: ClusterIP
  ports:
    - name: "443"
      port: 443
      targetPort: 443
    - name: "81"
      port: 81
      targetPort: 81
  selector:
    app: broker-reverseproxy
status:
  loadBalancer: {}
