apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
  labels:
    app: connectora
  name: connectora
spec:
  type: ClusterIP
  ports:
    - name: "http"
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: connectora
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
  labels:
    app: connectorb
  name: connectorb
spec:
  type: ClusterIP
  ports:
    - name: "http"
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: connectorb
status:
  loadBalancer: {}