apiVersion: v1
kind: Service
metadata:

  labels:
    app: omejdn
  name: omejdn
spec:
  type: ClusterIP
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: omejdn
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:

  labels:
    app: omejdn-ui
  name: omejdn-ui
spec:
  type: ClusterIP
  ports:
    - name: "8088"
      port: 8088
      targetPort: 8088
  selector:
    app: omejdn-ui
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: omejdn-server
  name: omejdn-server
spec:
  type: ClusterIP
  ports:
    - name: "4567"
      port: 4567
      targetPort: 4567
  selector:
    app: omejdn-server
status:
  loadBalancer: {}