apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ids-2
  labels:
    app: hostnames
  name: hostnames
spec:
  selector:
    matchLabels:
      app: hostnames
  replicas: 1
  template:
    metadata:
      labels:
        app: hostnames
    spec:
      containers:
      - env:
        - name: REMOTE_URL
          value: "http://127.0.0.1:443"
      
        name: hostnames
        image: foxylion/nginx-self-signed-https:latest
        ports:
          - containerPort: 443
            name: hostnames

        volumeMounts:
         - name: configmap-hostname
           mountPath: /etc/nginx/cert.crt
           subPath: tls-test.crt

         - name: configmap-hostname
           mountPath: /etc/nginx/cert.key
           subPath: tls-test.key

        # - name: configmap-hostname
        #   mountPath: /etc/nginx/conf.d/nginx.conf
        #   subPath: nginx.conf                    

      restartPolicy: Always
      volumes:
      - name: configmap-hostname 
        configMap:
          name: hostnames-config
            